// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AccountConfig.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "AccountConfig.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* AccountConfig_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  AccountConfig_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_AccountConfig_2eproto() {
  protobuf_AddDesc_AccountConfig_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "AccountConfig.proto");
  GOOGLE_CHECK(file != NULL);
  AccountConfig_descriptor_ = file->message_type(0);
  static const int AccountConfig_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, brokerid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, userid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, password_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, front_ip_),
  };
  AccountConfig_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      AccountConfig_descriptor_,
      AccountConfig::default_instance_,
      AccountConfig_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(AccountConfig, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(AccountConfig));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_AccountConfig_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    AccountConfig_descriptor_, &AccountConfig::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_AccountConfig_2eproto() {
  delete AccountConfig::default_instance_;
  delete AccountConfig_reflection_;
}

void protobuf_AddDesc_AccountConfig_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\023AccountConfig.proto\"U\n\rAccountConfig\022\020"
    "\n\010BrokerID\030\001 \001(\t\022\016\n\006UserID\030\002 \001(\t\022\020\n\010Pass"
    "word\030\003 \001(\t\022\020\n\010Front_IP\030\004 \001(\t", 108);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "AccountConfig.proto", &protobuf_RegisterTypes);
  AccountConfig::default_instance_ = new AccountConfig();
  AccountConfig::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_AccountConfig_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_AccountConfig_2eproto {
  StaticDescriptorInitializer_AccountConfig_2eproto() {
    protobuf_AddDesc_AccountConfig_2eproto();
  }
} static_descriptor_initializer_AccountConfig_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int AccountConfig::kBrokerIDFieldNumber;
const int AccountConfig::kUserIDFieldNumber;
const int AccountConfig::kPasswordFieldNumber;
const int AccountConfig::kFrontIPFieldNumber;
#endif  // !_MSC_VER

AccountConfig::AccountConfig()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:AccountConfig)
}

void AccountConfig::InitAsDefaultInstance() {
}

AccountConfig::AccountConfig(const AccountConfig& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:AccountConfig)
}

void AccountConfig::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  brokerid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  userid_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  front_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

AccountConfig::~AccountConfig() {
  // @@protoc_insertion_point(destructor:AccountConfig)
  SharedDtor();
}

void AccountConfig::SharedDtor() {
  if (brokerid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete brokerid_;
  }
  if (userid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete userid_;
  }
  if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete password_;
  }
  if (front_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete front_ip_;
  }
  if (this != default_instance_) {
  }
}

void AccountConfig::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* AccountConfig::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return AccountConfig_descriptor_;
}

const AccountConfig& AccountConfig::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_AccountConfig_2eproto();
  return *default_instance_;
}

AccountConfig* AccountConfig::default_instance_ = NULL;

AccountConfig* AccountConfig::New() const {
  return new AccountConfig;
}

void AccountConfig::Clear() {
  if (_has_bits_[0 / 32] & 15) {
    if (has_brokerid()) {
      if (brokerid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        brokerid_->clear();
      }
    }
    if (has_userid()) {
      if (userid_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        userid_->clear();
      }
    }
    if (has_password()) {
      if (password_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        password_->clear();
      }
    }
    if (has_front_ip()) {
      if (front_ip_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        front_ip_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool AccountConfig::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:AccountConfig)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string BrokerID = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_brokerid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->brokerid().data(), this->brokerid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "brokerid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_UserID;
        break;
      }

      // optional string UserID = 2;
      case 2: {
        if (tag == 18) {
         parse_UserID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_userid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->userid().data(), this->userid().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "userid");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_Password;
        break;
      }

      // optional string Password = 3;
      case 3: {
        if (tag == 26) {
         parse_Password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "password");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_Front_IP;
        break;
      }

      // optional string Front_IP = 4;
      case 4: {
        if (tag == 34) {
         parse_Front_IP:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_front_ip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->front_ip().data(), this->front_ip().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "front_ip");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:AccountConfig)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:AccountConfig)
  return false;
#undef DO_
}

void AccountConfig::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:AccountConfig)
  // optional string BrokerID = 1;
  if (has_brokerid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->brokerid().data(), this->brokerid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "brokerid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->brokerid(), output);
  }

  // optional string UserID = 2;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->userid().data(), this->userid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "userid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->userid(), output);
  }

  // optional string Password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->password(), output);
  }

  // optional string Front_IP = 4;
  if (has_front_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->front_ip().data(), this->front_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "front_ip");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->front_ip(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:AccountConfig)
}

::google::protobuf::uint8* AccountConfig::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:AccountConfig)
  // optional string BrokerID = 1;
  if (has_brokerid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->brokerid().data(), this->brokerid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "brokerid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->brokerid(), target);
  }

  // optional string UserID = 2;
  if (has_userid()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->userid().data(), this->userid().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "userid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->userid(), target);
  }

  // optional string Password = 3;
  if (has_password()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->password(), target);
  }

  // optional string Front_IP = 4;
  if (has_front_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->front_ip().data(), this->front_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "front_ip");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->front_ip(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:AccountConfig)
  return target;
}

int AccountConfig::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string BrokerID = 1;
    if (has_brokerid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->brokerid());
    }

    // optional string UserID = 2;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->userid());
    }

    // optional string Password = 3;
    if (has_password()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->password());
    }

    // optional string Front_IP = 4;
    if (has_front_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->front_ip());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void AccountConfig::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const AccountConfig* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const AccountConfig*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void AccountConfig::MergeFrom(const AccountConfig& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_brokerid()) {
      set_brokerid(from.brokerid());
    }
    if (from.has_userid()) {
      set_userid(from.userid());
    }
    if (from.has_password()) {
      set_password(from.password());
    }
    if (from.has_front_ip()) {
      set_front_ip(from.front_ip());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void AccountConfig::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AccountConfig::CopyFrom(const AccountConfig& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AccountConfig::IsInitialized() const {

  return true;
}

void AccountConfig::Swap(AccountConfig* other) {
  if (other != this) {
    std::swap(brokerid_, other->brokerid_);
    std::swap(userid_, other->userid_);
    std::swap(password_, other->password_);
    std::swap(front_ip_, other->front_ip_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata AccountConfig::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = AccountConfig_descriptor_;
  metadata.reflection = AccountConfig_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
